#spring
server:
  port: 8001
  host: 192.168.95.132
  es_port: 30080

# elasticsearch配置
spring:
  data:
    elasticsearch:
      cluster-name: k8s-es-cluster
      cluster-nodes: ${server.host}:30070
      repositories:
        enabled: true

  elasticsearch:
      hostlist: ${server.host}:${server.es_port}
      rest:
        uris: ["http://${server.host}:${server.es_port}"]

  redis:
    host: localhost
    database: 1
    port: 6379
    password:

#swagger
swagger:
  enable: true
  host: localhost
  version: 1.0.0
  title: 接口文档
  description: 描述
  license: ZZZ
  licenseUrl: http://zzzserver.com/8001/swagger-ui.html
  termOfServiceUrl: http://zzzserver.com