spring:
  servlet:
    multipart:
      # 上传一个文件最大值,默认1Mb
      max-file-size: 50MB
      # 上传多个文件最大值,50Mb,默认10Mb
      max-request-size: 100MB
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

  application:
    name: test-mybatis

  datasource:
    url: jdbc:mysql://localhost/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true
    username: root
    password: xfwan
    #  连接池的配置信息
    initialSize: 10
    minIdle: 10
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 300000
    minEvictableIdleTimeMillis: 3600000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    time-zone: "GMT+8"
    date-format: "yyyy-MM-dd HH:mm:ss"


server:
  port: 8000
  # 下面这个参数是为解决问题而新增的
  max-http-header-size: 809600
  servlet:
    session:
      cookie:
        path: /
        secure: false
      timeout: -1

mybatis-plus:
  mapper-locations: classpath:mapper/*/*.xml
  mapper-refresh: true
  type-aliases-package: com.github.trang.typehandlers.alias
  type-handlers-package: ai.bailian.bidding.insurance.config.mybatis.typehandler
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 0
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
  #    capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl