server:
  port: 8181

# elastic job
spring:
  elasticjob:
    zookeeper:
      server-lists: localhost:2181
      namespace: demo-job

  datasource:
    url: jdbc:mysql://localhost/xxl_job?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: xfwan
    #  连接池的配置信息
    initialSize: 10
    minIdle: 10
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 300000
    minEvictableIdleTimeMillis: 3600000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    driver-class-name: com.mysql.cj.jdbc.Driver